spring.application.name=email-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/email_db
spring.datasource.username=root
spring.datasource.password=Sud123@123sud

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sy0205476@gmail.com
spring.mail.password=gcyixqlgkfwaduki

app.base-url= https://twins-phosphate-jugular.ngrok-free.dev

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true